### ISSUE TITLE
lodash dependency only for a for() ?

### ISSUE THREAD

**Issue by stevenvachon** [devrchancay/emotsjs#3]
That's kind of silly.

**Comment by devrchancay** [comment]
:sob: if they are thought to do something else and forget soon take away :smile:  thanks

**Comment by stevenvachon** [comment]
?

It's used for `all()` to convert an Object to an Array. Anyone who wants to use this in a browser is gonna be forced to include Lodash. Poor design decision.

**Comment by devrchancay** [comment]
solved thanks @stevenvachon

**Comment by stevenvachon** [comment]
:+1:
